apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: "team1"
  name: "podinfo-ingress"
  labels:
    app: podinfo
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: team1.192.168.68.212.nip.io
    http:
      paths:
        - backend:
            serviceName: podinfo
            servicePort: 80